steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'web-server'
    - '--image'
    - 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA'
    - '--region'
    - 'us-west1'
    - '--platform'
    - 'managed'
  images:
  - 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA'